name: "Yandex backup"
description: "Copy HA backup to YandexDisk"
version: "2.01.3"
slug: "yabackup"
url: "https://github.com/maxifly/YaBackupAddon/tree/main/yabackup"
image: "ghcr.io/maxifly/yabackupaddon/yabackup-{arch}"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - backup

homeassistant_api: true
hassio_api: true
hassio_role: "admin"

options:
  client_id: 0
  client_secret: 0
  remote_path: "/ha_test"
  remote_maximum_files_quantity: 10
  schedule: "1 2 * * *"
  upload_from_network_storage: false
  enabled_network_storages: []
  log_level: INFO
  theme: Light

schema:
  client_id: str
  client_secret: str
  remote_path: str
  remote_maximum_files_quantity: "int(0,)"
  schedule: str
  upload_from_network_storage: bool
  enabled_network_storages:
    - name: str
  log_level: "list(DEBUG|INFO|WARNING|ERROR)"
  theme: "list(Light|Dark)"
  entity_id: "str?"

ingress: true
