name: "Yandex backup"
description: "My first real add-on!"
version: "1.0.1"
slug: "yabackup"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int

startup: before

ingress: true
