name: "Yandex backup"
description: "My first real add-on!"
version: "1.0.1"
slug: "yabackup"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - backup

options:
  client_id: 0
  client_secret: 0
  remote_path: "/ha_test"
  schedule: "1 2 * * *"

schema:
  client_id: str
  client_secret: str
  remote_path: str
  schedule: str

startup: before

ingress: true
